use_frameworks!

platform :ios, '9.0'

target 'MGTestPod_Example' do
  pod 'Folly', :podspec => '/Users/liming/Desktop/MGTestPod/Example/MGTestPod/Folly.podspec'

  target 'MGTestPod_Tests' do
    inherit! :search_paths

    

  end
end
